version: "3.8"

services:
  express-bk:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - postgres-db
    volumes:
      - .:/app
      - /app/node_modules

  postgres-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shoppinglist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
